title: Obsidian Nightfall
description: >-
  An elegant, dark theme created by Volkan Sah, perfect for a modern and sleek user experience. It provides a visually pleasing interface with a focus on readability and style.
baseurl: "/Obsidian-Nightfall" # The name of your repository
url: "https://volkansah.github.io" # Your GitHub Pages URL
theme: minima # Or your custom theme, e.g., "obsidian-nightfall" if developed. ddefault 

kramdown:
  input: GFM
  math_engine: mathjax
  # alternativ: math_engine: katex
  # math_engine_opts: {}  # nur wenn n√∂tig
# --- remaining config entries below ---

